apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: web-platform
data:
  AUTH_SERVICE_URL: http://auth-service:5000
  AGENDA_SERVICE_URL: http://agenda-service:5000
  CONTACT_SERVICE_URL: http://contact-service:5000
  INTEGRATIONS_SERVICE_URL: http://integrations-service:5000
  NOTIFICATIONS_SERVICE_URL: http://notifications-service:5000
  REQUEST_TIMEOUT: "10"
  AGENDA_REQUEST_TIMEOUT: "5"
  USERS_CSV_PATH: /app/data/users.csv
  CONTACT_CSV_PATH: /app/data/contact_messages.csv
  GUNICORN_WORKERS: "2"
  GUNICORN_THREADS: "4"
  GUNICORN_TIMEOUT: "60"
