name: CI-CD auth-service

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar repo
      - name: Checkout
        uses: actions/checkout@v3

      # 2. Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Instalar dependencias (PRO + DEV)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Docker-Microservices/requirements.txt
          pip install pytest requests werkzeug

      # 4. Tests
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/Docker-Microservices
          pytest -v --maxfail=1 --disable-warnings

      # 5. Login Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 6. Login ACR
      - name: Login ACR
        run: az acr login --name PracticaProduccion

      # 7. Build Docker (IMPORTANTE ruta /auth)
      - name: Build image
        run: docker build -t practicaproduccion.azurecr.io/auth-service:v1 ./auth

      # 8. Push Docker
      - name: Push image
        run: docker push practicaproduccion.azurecr.io/auth-service:v1